name: Publish Python Package

on:
  push:
    branches:
      - main  # Modifiez cela si vous publiez depuis une autre branche

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Nécessaire pour OpenID Connect
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Modifiez selon votre besoin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
