name: Python package

on:
  push:
    branches:
      - main  # Changez cela selon votre branche de publication

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Changez cela selon la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPi
      run: |
        python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__  # Utilisez "__token__" comme nom d'utilisateur pour l'API token
        TWINE_PASSWORD: ${{ PIPY-API-TOKEN}}  # Définissez le secret PYPI_API_TOKEN dans vos secrets GitHub
